name: "cleanup"
shortDesc: "cleanup plug-in"
longDesc: "Clean up excessive (stale) resources."
example: "oc plugin cleanup"
command: "./cleanup.sh"
flags:
  - name: "force"
    shorthand: "f"
    desc: "don't ask for confirmation to delete image tags (use: y)"
    defValue: "n"
  - name: "git-repo-path"
    shorthand: "p"
    desc: "absolute path to Git repository (for current dir use: $PWD)"
  - name: "keep"
    shorthand: "k"
    desc: "keep most current <n> images"
    defValue: "3"
