name: "cleanup"
shortDesc: "cleanup plug-in"
longDesc: "Clean up excessive (stale) image tags, images and related resources."
example: "oc plugin cleanup IMAGE --git-repo-path $PWD"
command: "./cleanup.sh"
flags:
  - name: "force"
    shorthand: "f"
    desc: "don't ask for confirmation to delete image tags (use: y)"
    defValue: "n"
  - name: "git-commit-limit"
    shorthand: "l"
    desc: "only look at the first <n> commits to compare with tags"
    defValue: "100"
  - name: "git-repo-path"
    shorthand: "p"
    desc: "absolute path to Git repository (for current dir use: $PWD)"
  - name: "keep"
    shorthand: "k"
    desc: "keep most current <n> images"
    defValue: "10"
